import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :cloud_db_ui, CloudDbUiWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API client.
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: CloudDbUi.Finch

# Disable Swoosh local memory storage (enabled because
# of `adapter: Swoosh.Adapters.Local`)
config :swoosh, local: true

# Do not print debug messages in production.
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
